Test
Altu-Bitu/Altu-Bitu-HW pull request #12
Opened 2021-10-04 02:25 UTC by mkwkw

다른 문제들은 오늘 자정까지 해서 다 풀도록 하겠습니다!
20923이 마지막 테스트 케이스가 답이 안 나오기는하는데 제가 코드 작성한 것이 이 문제를 해결하는 코드와 전반적인 흐름이 맞는 것인지 궁금합니다. 원래 코드가 이렇게 길게 나오는 것인지 아니면 제가 너무 복잡하게 작성한 것인지도 궁금합니다.

2021-10-04 05:26 UTC, bsa0322 requested changes
p1. 20923 수정하시다가 안되는 부분 있으면 말씀해주세요!! 수고하셨습니다!! 

더불어 코드 그렇게 긴 편 아니에요! 지금 딱 필요한 부분만 들어가 있어요! 사실 도도와 수연이의 덱과 그라운드를 배열로 관리하면 코드가 훨씬 줄어들 수 있긴 한데, 나중에 샘플코드 확인하시면 좋을 것 같아요. 우선 지금 코드도 복잡한 편 아니니까 해결할 수 있어요!!

2021-10-04 05:26 UTC, bsa0322 commented on 9월 28일-동적 계획법/20923.cpp
> +    for(int i=0; i<2500000; i++){
p1. m번 턴을 돌면 무조건 종료해야 하기 때문에 여기 조건에 맞게 반복문을 설정해주셔야 해요!

2021-10-04 05:26 UTC, bsa0322 commented on 9월 28일-동적 계획법/20923.cpp
> +        }
p1. 여기서 empty()확인을 하게 되면, 도도와 수연이 모두 덱에서 카드를 빼온 후 하게 돼요. 그런데 문제에서는 둘 중 하나의 덱이라도 비면 바로 종료를 해야 한다 했죠! 그렇다면 어디서 empty()확인을 해야 할까요? 지금 코드에선 2번 들어가야 해요. 그리고 empty()면 바로 종료를 시켜줘야 해요! 반복문을 빠져나오는거죠.

\+ 아래 코드 확인해보니 empty()확인이 잘 들어갔네요! 그렇다면 여기서 확인은 굳이 필요 없어요! 그리고 말씀드렸듯이 바로 반복문을 빠져나오도록 해야 해요!

2021-10-04 05:26 UTC, bsa0322 commented on 9월 28일-동적 계획법/20923.cpp
> +            arr[i]="dosu";
p1. 이 확인도 반복문을 빠져나온 후에 해야 해요! 모든 턴이 끝나거나 아니면 둘 중 한 사람의 덱이 비어서 빠져나온 경우에요!

2021-10-04 13:07 UTC, mkwkw commented
멘토님 의견 참고하고 디버깅 해가면서 최대한 제 사고의 흐름에 따라 코드를 작성하였는데요. 틀렸다고 하네요ㅠ
그리고 이상한 점이 있습니다. 첫 번째 테스트 케이스를 넣어봤을 때 제가 직접 노트에 작성한 바로는 i=7번째에 도도의 덱에는 12개, 도도의 그라운드에는 0개, 수연의 덱에는 8개, 수연의 그라운드에는 0개의 카드가 있어야되는데 75번째와 82번째 줄의 for문 조건을 각각 j<q1.size() 와 j<q2.size()로 하면 각각의 그라운드의 카드가 모두 도도의 덱으로 이동하지 않고 각각의 그라운드에 카드가 1개씩 남게 됩니다. 다 없애려면 제가 현재 해당 줄에 써놓은 것처럼 +2, +1을 해야 되는데요. 아무리 봐도 이상한 것 같아요. 이렇게 백준에 돌리면 segment fault가 나고 +2, +1을 지우고 돌리면 틀렸습니다가 뜹니다. 어디서 오류가 난 것일까요?

2021-10-04 13:23 UTC, bsa0322 requested changes
코멘트 남겼어요!! 하다가 안되면 또 질문 주세요! 퐈이팅! 할 수 있어요!!!

2021-10-04 13:23 UTC, bsa0322 commented on 9월 28일-동적 계획법/20923.cpp
> +            for(int j=0; j<q2.size(); j++) { //�� �׶��忡 �ִ� ī��� �� �������
queue 순회를 해주실 때는 이렇게 하는 것보다 queue가 empty()한지 체크하는 while문으로 해주시는게 좋아요!!!!!! 아마 while(!q2.empty()) 형식으로 하면 오류도 안 날 거에요!

2021-10-04 13:23 UTC, bsa0322 commented on 9월 28일-동적 계획법/20923.cpp
> +string arr[2500001];
정답은 배열로 관리할 필요가 없어요! m번 진행하거나 혹은 둘 중 하나의 덱이 비어 빠져나온 상태에서 도도와 수연이의 덱에 얼마가 남았는지를 확인해서 do, su, dosu를 출력하면 돼요~!

2021-10-04 13:23 UTC, bsa0322 commented on 9월 28일-동적 계획법/20923.cpp
> +        if(a+b==5){
그리고 아마 이 부분에서도 문제가 나는 것 같아요! 지금 전에 저장되어있는 그라운드 값을 활용하여 비교해주고 있는데, 그 사이 누가 종을 쳐서 그라운드가 어떻게 변할지 모르는 일이죠. 따라서 항상 현재 empty()체크도 해주고, 현재 값으로 비교해주어야 해요!!! 
그러면 그라운드의 가장 뒤인 back()에 접근해야겠죠? 그래서 그라운드를 deque로 관리하는 게 좋아요!

2021-10-04 13:23 UTC, bsa0322 commented on 9월 28일-동적 계획법/20923.cpp
> +        ++i;
여기서 m번이 될 수도 있지 않을까요?

2021-10-04 13:23 UTC, bsa0322 commented on 9월 28일-동적 계획법/20923.cpp
> +        //++i;
수연이의 턴이 끝난 후에도 ++i를 해주어야 해요!!

2021-10-04 14:25 UTC, mkwkw commented
코드 바꿔봤는데도 틀렸습니다가 뜨네요ㅠㅠ 전에는 4%에서 떴다면 지금은 38%에서 틀렸습니다가 뜨는 정도로 발전하긴했지만요..  어디서 틀린 것일까요? 큐에서도 back을 사용할 수는 있어서 큐는 그대로 사용했는데 그라운드도 덱으로 바꿔야 맞는 걸까요?

2021-10-04 15:08 UTC, bsa0322 requested changes
말씀하신 것처럼 그라운드를 queue로 구현해도 풀 수 있어요!! 지금 종을 치는 부분과 종료 조건이 제대로 설정이 안 된 것 같아요. 그리고 for문과 i%2의 값으로 순서를 관리해주고 있으니 굳이 250000~ 까지 돌릴 필요 없이 m까지 돌리는 건 어떨까요? 그럼 cnt변수 사용도 없어질 것 같아요~!!
조금만 더 수정하면 맞을 것 같아요. 할 수 있어요!!!!

2021-10-04 15:08 UTC, bsa0322 commented on 9월 28일-동적 계획법/20923.cpp
> +                break;
종료조건이 적절하지 않네요! cnt=1 로 초기화를 해주셨네요! 그렇다면 실제 횟수가 m번과 같다는 건 어떻게 판단할까요? 아니면 cnt초기화 값을 변경해주셔도 좋아요

2021-10-04 15:08 UTC, bsa0322 commented on 9월 28일-동적 계획법/20923.cpp
> +            if (a + b == 5) {
그라운드에서 덱에 넣을 때, a와 b값을 갱신해도 의미가 없어요....! 그라운드는 다 사라질 테니까요. 여기서 더 중요한 건 empty()체크였어요! 말씀하신것처럼 queue도 back에 접근할 수 있죠. 그러니 조건문에서 바로 empty 체크와 함께 back에  접근하면 좋을 것 같아요.

2021-10-04 15:56 UTC, mkwkw commented
아 그리고 말씀드리는 것 잊어버렸었는데 12시 되기 전에 10844 풀어서 제출했습니다!

2021-10-04 16:21 UTC, mkwkw commented
empty조건 넣어봤는데도 안되네요ㅠ 계속 38%에서 틀렸습니다가 뜹니다.. 샘플 코드 보고 주석 달아서 올리겠습니다..!!

2021-10-04 16:38 UTC, bsa0322 approved these changes
넵! 10844 제출 확인 했습니다. 

20923은 진짜 조금만 수정하면 맞을 수 있어요..!!!!! 우선 empty체크는 그라운드의 back에만 접근하는거니 그라운드만 해주면 되고, 현재 m턴까지 도는 부분을 반복문으로 체크해주셨으니 cnt변수는 필요없어요..! 그래서 사용하지 않으므로 지워주어야 해요. 그리고 덱에서 그라운드로 낸 다음엔 항상 덱이 비어있는지 체크해줘서 종료조건을 걸어주어야 하는데 수연이 쪽에만 있고 도도 턴에는 없네요..! 

허헣,,,암튼 너무 너무 수고 많으셨어요,,,, 머지해주셔도 괜찮아요!! 나머지는 추가제출 해주세요! 수고하셨습니다~~!!!!!!

2021-10-05 07:09 UTC, mkwkw commented
와.. 말씀대로 수연이쪽에 덱 비었는지 확인하고 종료하는 문장 해주니까 맞았습니다 떴어요!! 감사합니다!! 당연히 수연이쪽에도 이 조건문 썼는 줄 알았는데 안써놨었네요...ㅎㅎ 어쨌든 코드리뷰 감사합니다! 노력 끝에 맞았습니다 뜨니까 기분 좋네요~~

2021-10-05 07:12 UTC, merged

2021-10-05 07:19 UTC, bsa0322 commented
다행이네요! 20923, 10844 제외하고 추가제출 해주시면 될 것 같아요. 넘 수고하셨습니다~!!