[최소 신장 트리] 12월 4일
Altu-Bitu/Altu-Bitu-HW pull request #21
Opened 2021-12-06 02:25 UTC by mkwkw

2021-12-06 11:52 UTC, HyunJiLim0406 requested changes
p1
수고하셨습니다~ 다만 풀어주신 코드가 레퍼런스 코드와 매우 유사하기 때문에 리팩토링을 해주셔야 해요. 타인의 코드를 가장 잘 이해하는 방법은 그 코드의 아쉬운 점을 발견해서 수정하는 것입니다!

2021-12-06 11:52 UTC, HyunJiLim0406 commented on 11월 30일-최소 신장 트리/1713.cpp
> +int main(){
레퍼런스 코드랑 좀 많이 비슷하네요! 리팩토링을 해볼까요? 이 코드는 for문과 if문이 복잡하게 얽혀 있어서 좋은 코드는 아니예요
일단 사진틀에 학생이 있는 경우와 없는 경우로 나눠볼까요? 있는 경우라면 그냥 추천수만 올리고 끝나면 돼요.
없다면, 사진틀이 꽉찬 경우와 아닌 경우로 나눠야겠네요. 이 모든 연산을 하나의 중괄호 안에 넣지 말고 continue로 끊거나 함수화 하며 리팩토링 해보세요!

2021-12-06 13:37 UTC, mkwkw commented
main에 있던 것을 나누어서 함수화해보았습니다. 함수화하니까 보기가 더 편한 것 같네요!

2021-12-06 15:25 UTC, HyunJiLim0406 reviewed
수고하셨습니다! 잘 수정하셨지만 이건 각 연산을 그냥 함수에 옮긴 것과 같아요!
이 코드의 문제점은 조건문이 얼기설기 얽혀있다는 것이고 그걸 푸는게 중요해요
어려우시다면 샘플코드 보고 수정해주세요~

2021-12-07 06:23 UTC, mkwkw commented
샘플코드 보고 주석달아서 추가제출합니다~

2021-12-19 10:44 UTC, mkwkw commented
슬랙에 추가제출 글 올렸었는데 확인이 안 되어있어서 re-request 해봅니다~

2021-12-19 13:22 UTC, HyunJiLim0406 reviewed
확인했습니다! 머지해주세요~

2021-12-19 14:40 UTC, mkwkw commented
감사합니다!

2021-12-19 14:40 UTC, merged