맵, 셋 pr
Altu-Bitu/Altu-Bitu-HW pull request #3
Opened 2021-09-13 02:30 UTC by mkwkw

19636 틀렸습니다가 뜨는데 이유를 모르겠습니다..

2021-09-13 10:08 UTC, Yuna9949 requested changes
p2. 전체적으로 열심히 잘 풀어주셨어요.
코멘트 참고하셔서 안되던 부분 수정해주시고 알려주시면 다시 코멘트 해 드리겠습니다.
다음에는 선택 3개도 해주세요!

2021-09-13 10:08 UTC, Yuna9949 commented on 9월7일-맵,셋/10757.cpp
> +string func(string a, string b){
함수이름은 그냥 func보다는 그 특성에 맞게 지어주시면  좋을 것 같아요

2021-09-13 10:08 UTC, Yuna9949 commented on 9월7일-맵,셋/10757.cpp
> +
좋은 전략이에요. 하지만 역순으로 옮기는 과정에서 연산 시간과 메모리가 소요될 것 같아요.
옮기는 작업 없이 진행할 수 있는 방법은 없을까요?

2021-09-13 10:08 UTC, Yuna9949 commented on 9월7일-맵,셋/10757.cpp
> +
마찬가지로 숫자로 변환했다가 문자로 도로 변환하는 과정에서 연산 시간과 메모리가 소요돼요.

2021-09-13 14:59 UTC, mkwkw commented on 9월7일-맵,셋/10757.cpp
> +
그럼 역순으로 옮긴 후에 다시 원래 순서로 옮기는 것보다 원래 상태에서 뒷부분부터 조사하는 게 더 효율적인 방법일까요?  이 생각이 일단 먼저 들어서 조금 더 생각해보도록 하겠습니다! 피드백 감사합니다~

2021-09-14 03:41 UTC, Yuna9949 requested changes
p2. 아직 10757번 수정이 덜 끝났네요. 마저 수정하고 알려주세요.
19636은 잘 수정하셨습니다!

2021-09-14 03:41 UTC, Yuna9949 commented on 9월7일-맵,셋/19636.cpp
> +            l2 = l2 + floor(((double)(l - (l2 + a)) / 2));
좋아요

2021-09-14 03:41 UTC, Yuna9949 commented on 9월7일-맵,셋/10757.cpp
> +
좋은 아이디에요. 이 부분도 마저 수정하면 알려주세요!

2021-09-16 14:42 UTC, mkwkw commented
10757 문제 수정하지 못했습니다.
스택, 큐, 덱 문제 포함되어있고
우선순위 큐 필수 문제 하나 포함되어 있습니다.
다음에는 제대로 나누어서 pr하도록 하겠습니다!

2021-09-16 14:42 UTC, merged