우선순위 큐
Altu-Bitu/Altu-Bitu-HW pull request #4
Opened 2021-09-20 02:53 UTC by mkwkw

2021-09-20 07:28 UTC, HyunJiLim0406 requested changes
p1
수고하셨습니다~ 효율성 면에서 더 리팩토링할 부분이 보이네요!
자세한 코멘트들은 코드에 달아놓았으니 확인해주세요!

수정 후 리뷰어로 저 호출해주세요

즐추~~~!!

2021-09-20 07:28 UTC, HyunJiLim0406 commented on 9월14일-우선순위 큐/11286.cpp
> +    priority_queue<int> pq2; //��� ��� �켱��� ť-������� ex. -1, -2, -3
p1
잘풀어주셨어요! 하지만 이 문제는 compare 함수를 정의해보는 문제였어요!
그럼 코드도 훨씬 짧아질거예요 다시 풀어볼까요?

2021-09-20 07:28 UTC, HyunJiLim0406 commented on 9월14일-우선순위 큐/12018.cpp
> +    }
여길 while문으로 하면 else-break가 없어도 되겠네요!

2021-09-20 07:28 UTC, HyunJiLim0406 commented on 9월14일-우선순위 큐/15903.cpp
> +        sort(v.begin(), v.end()); //�ٽ� ���
p2
굳이 반복해서 정렬할 필요가 있을까요?

2021-09-20 07:28 UTC, HyunJiLim0406 commented on 9월14일-우선순위 큐/3613.cpp
> +        }
p2
이 부분의 시간복잡도가 최대 O(n^2)이네요! 더 효율적으로 할 수 있는 방법은 없을까요?

2021-09-20 07:28 UTC, HyunJiLim0406 commented on 9월14일-우선순위 큐/3613.cpp
> +}
judging 함수에서 모든 에러를 처리하고 이 함수에서는 변환만 하는건 어떨까요?

2021-09-20 12:03 UTC, mkwkw commented on 9월14일-우선순위 큐/15903.cpp
> +        sort(v.begin(), v.end()); //�ٽ� ���
제일 작은 것들끼리 더한 것이 원래 배열의 세 번째 작은 수보다 클수도 있으니까 반복해서 정렬해야한다고 생각했습니다. 반복해서 정렬할 필요가 없는 것일까요?

2021-09-20 12:17 UTC, HyunJiLim0406 commented on 9월14일-우선순위 큐/15903.cpp
> +        sort(v.begin(), v.end()); //�ٽ� ���
반복해서 정렬을 하긴 해야해요! 근데 벡터를 사용해서 굳이 매번 정렬할 필요는 없단 뜻이에요~

2021-09-20 12:24 UTC, mkwkw commented on 9월14일-우선순위 큐/15903.cpp
> +        sort(v.begin(), v.end()); //�ٽ� ���
아하 그럼 벡터를 우선순위 큐로 바꾸면 더 효율적인 코드가 될까요?

2021-09-20 12:33 UTC, HyunJiLim0406 commented on 9월14일-우선순위 큐/15903.cpp
> +        sort(v.begin(), v.end()); //�ٽ� ���
네!

2021-09-20 13:40 UTC, mkwkw commented on 9월14일-우선순위 큐/3613.cpp
> +        }
judging에서 모든 오류 처리하는 것까지는 했는데 이 이중for문을 어떻게 없앨 수 있을지 모르겠네요.. 제가 생각해도 시간복잡도는 줄일 수 있을 것 같은데 아이디어가 안떠오릅니다. 그나마 투 포인터가 생각이 나서 해보려고 하는데 시간복잡도가 줄어들지 모르겠네요..

2021-09-20 14:09 UTC, HyunJiLim0406 commented on 9월14일-우선순위 큐/3613.cpp
> +        }
아예 관점을 바꿔보는건 어떨까요?
조건을 거치면서 어떤 언어인지 알아내는게 아니라 '이건 어떤 언어일거야'라고 가정하고 내 판단이 맞는지 확인하는거예요!

2021-09-21 14:34 UTC, mkwkw commented
3613문제의 코드는 과제 샘플 코드 이용해서 수정했고 주석들 달았습니다! 추석연휴인데 고생많으시네요.. 언니도 남은 연휴 즐추~~

2021-09-21 14:58 UTC, HyunJiLim0406 reviewed
p3
머지해도 됩니다!
그래도 샘플코드는 한번씩 봐주세요~!
남은 연휴 즐추!! 😉

2021-09-21 14:58 UTC, HyunJiLim0406 commented on 9월14일-우선순위 큐/11286.cpp
> +        else //����� �ٸ� ���
if 문에 걸리면 부조건 true/false를 리턴하기 때문에 이 else는 필요없습니다!
그리고 샘플코드 봐주세요! 굳이 abs를 따로 저장할 필요는 없어요~

2021-09-21 14:58 UTC, HyunJiLim0406 commented on 9월14일-우선순위 큐/12018.cpp
> +    }
👍

2021-09-21 14:58 UTC, HyunJiLim0406 commented on 9월14일-우선순위 큐/15903.cpp
> +    }
👍

2021-09-22 02:22 UTC, mkwkw commented on 9월14일-우선순위 큐/11286.cpp
> +        else //����� �ٸ� ���
샘플 코드 보고 수정했습니다. compare함수가 익숙하지 않아서 이렇게 썼었는데 샘플코드 보니까 더 간단하게 만들 수 있었네요!

2021-09-22 02:22 UTC, merged